Add confirmation msg to the scan folder function + readme

diff --git a/quickdock b/quickdock
--- a/quickdock
+++ b/quickdock
@@ -41,11 +41,24 @@ main() {
                 logger "Started !"
             fi
         ;;
-        yarn)
-            # if yarn, we search a node container
+        yarn | npm)
+            # if yarn or npm, we search a node container
             container_name=$(extract_node_container_name "$compose_path")
         ;;
     esac
+
+    if [ "$container_name" = '' ]; then
+        logger "ERROR : can't find a container for the command : $1"
+        case $1 in
+            artisan | composer)
+                logger "Make sure the PHP container name is suffixed by '-php'"
+            ;;
+            yarn | npm)
+                logger "Make sure the NODE container name is suffixed by '-node'"
+            ;;
+        esac
+        exit 1
+    fi
 
     # Based on the first argument, we run the correct command
     local msg=''
@@ -56,7 +69,7 @@ main() {
         composer)
             msg=$(run_docker_compose_composer_cmd "$compose_path" "$container_name"  "$*")
         ;;
-        yarn)
+        yarn | npm)
             msg=$(run_docker_compose_node_cmd "$compose_path" "$container_name"  "$*")
         ;;
         *)
@@ -81,7 +94,7 @@ run_docker_compose_artisan_cmd() {
 run_docker_compose_composer_cmd() {
     do_cmd "docker-compose -f $1 --project-directory $(dirname "$1") exec $2 $3"
 }
-# Run docker-compose run --rm --services-ports `given container name` yarn `given command`
+# Run docker-compose run --rm --services-ports `given container name` (yarn | npm) `given command`
 run_docker_compose_node_cmd() {
     do_cmd "docker-compose -f $1 --project-directory $(dirname "$1") run --rm --service-ports $2 $3"
 }
@@ -115,15 +128,21 @@ climb_to_composer_laravel() {
     local composer_file_path
     while [ $found = false ]; do
         cd ..
-        # We search a file named composer.json in the current folder WITHOUT going to childrens (were we come from)
+        # We search a file named composer.json in the current folder WITHOUT going to childrens (where we come from)
         composer_file_path=$(find "$(pwd)" -maxdepth 1 -type f -name 'composer.json')
         if [ "$composer_file_path" != '' ]; then
             # Even if a composer.json is composer.json file is found,
             # we need it to require laravel/framework in order to use artisan command
             # TODO : Need to find another way as yarn container don't need Laravel !
             if grep -q "laravel/framework" "$composer_file_path"; then
-                found=true
-                return 0
+                local test
+                # Ask the user if the folder we found the composer.json in is the correct folder
+                # If not, we continue to climb !
+                test=$(ask_confirm "Composer.json file found in : $(dirname "$composer_file_path"), use this folder ?")
+                if [ "$test" = 'Y' ] || [ "$test" = 'y' ]; then
+                    found=true
+                    return 0
+                fi
             fi
         fi
 
@@ -135,6 +154,16 @@ climb_to_composer_laravel() {
     done
 }
 
+# This helper ask a user input with the first param as question
+# If no response is given, Y (yes) is assumed
+ask_confirm() {
+    read -rp "$1 [Y/n]: " response
+    if [ "$response" = '' ]; then
+        response='Y'
+    fi
+    echo "$response"
+}
+
 # This helper is used to print string to stderr without messing with function return
 # https://superuser.com/a/1320694
 # Can /dev/tty be used ?
@@ -144,15 +173,14 @@ logger() {
 
 
 case $1 in
-        artisan | composer | yarn)
+        artisan | composer | yarn | npm)
             main "$@"
-
         ;;
         help)
             logger "HELP ME PLEASE !..."
         ;;
         *)
             logger "Invalid command..."
-            logger "The first parameter must be one the list : [ artisan | composer | yarn ]"
+            logger "The first parameter must be one the list : [ artisan | composer | yarn | npm ]"
         ;;
     esac
